#https://adamtheautomator.com/postgres-to-kubernetes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresqlpv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: postgresstorage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/cristiansanchez/data/volume"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqlpvc
  labels:
    app: postgres
spec:
  storageClassName: postgresstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrescm
  labels:
    app: postgres
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: strongpasswordapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgrescm
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresqlpvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgressvc
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30000
  selector:
    app: postgres

# CREATE TABLE public.ticket
# (
#     id serial NOT NULL,
#     "position" character varying,
#     name character varying,
#     PRIMARY KEY (id)
# );
#
# ALTER TABLE IF EXISTS public.ticket
#     OWNER to appuser;

# -- Table: public.bank_account
#
# -- DROP TABLE IF EXISTS public.bank_account;
#
# CREATE TABLE IF NOT EXISTS public.bank_account
# (
#     id integer NOT NULL DEFAULT nextval('bank_account_id_seq'::regclass),
#     account_number character varying COLLATE pg_catalog."default",
#     name character varying COLLATE pg_catalog."default",
#     balance numeric,
#     CONSTRAINT bank_account_pkey PRIMARY KEY (id),
#     CONSTRAINT unique_account_number UNIQUE (account_number)
# )
#
# TABLESPACE pg_default;
#
# ALTER TABLE IF EXISTS public.bank_account
#     OWNER to appuser;